### ISSUE TITLE
My kingdom for a build

### ISSUE THREAD

**Issue by gmenier** [jkavalik/GcodeThumbnailExtension#1]
Hi jkavalik, 
not really an issue, just a request. Could you (please please) drop a built dll for your project : it would be very usefull 'cause I do not manage the %$! installation process for the right skd with the right msbuilt etc..
Thank you for your project - and keep 3D printing :-)
Regards
Gildas

**Comment by jkavalik** [comment]
@gmenier thanks for checking! The dll and install script ( a batch file) should be available for download in releases tab.

**Comment by gmenier** [comment]
Oh yeah great :-) Thank you !!
