### ISSUE TITLE
GcodeThumbnailExtension.dll does not exist

### ISSUE THREAD

**Issue by titust1** [jkavalik/GcodeThumbnailExtension#2]
You want to register a dll in the batch file, but you do not provide the dll. GcodeThumbnailExtension.dll does not exist in this zip file

**Comment by jkavalik** [comment]
Hello, which zip file do you mean? Did you maybe download the sources instead of the release zip?
I just checked and it is present in https://github.com/jkavalik/GcodeThumbnailExtension/releases/download/v1.0/v1.0.zip

**Comment by jkavalik** [comment]
No response, closing.
